import { Button } from "std-widgets.slint";
import { ShellAPI } from "api.slint";

export component Dock inherits Window {
    Rectangle {
        background: black;

        txt := Text {
            text: "2 + 3 = ";
            color: white;
        }
        
        Button {
            clicked => {
                txt.text = "2 + 3 = " + ShellAPI.add_numbers(2, 3);
            }
        }
    }
}
