import { ShellAPI } from "api.slint";
import { HorizontalBox, GroupBox } from "std-widgets.slint";
import { IconButton } from "widgets/icon_button.slint";
import { ControlCenter } from "widgets/control_center.slint";
import { Clock } from "widgets/clock.slint";

export component Dock inherits Window {
    background: transparent;

    Rectangle {
        background: #262626aa;

        HorizontalBox {
            alignment: start;
            padding: 5px;
            IconButton {
                width: self.height;
                alt-highlight: true;
                icon-source: @image-url("assets/widgets.svg");

                clicked => {
                    
                }
            }
        }

        HorizontalBox {
            alignment: center;
            padding: 5px;
            width: self.height;
            IconButton {
                alt-highlight: false;
                icon-source: @image-url("assets/launcher.svg");

                clicked => {
                    
                }
            }
        }

        HorizontalBox {
            alignment: end;
            padding: 0px;

            HorizontalBox {
                padding: 5px;
                IconButton {
                    alt-highlight: true;
                    width: self.height;
                    icon-source: @image-url("assets/expand.svg");

                    clicked => {
                        
                    }
                }
                ControlCenter {
                    width: 42px * 2;
                }

                Clock {}
            }
            

            
        }
    }
}